# Generated by Django 2.1.11 on 2019-08-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='file',
            field=models.FileField(default='', null=True, upload_to=''),
        ),
    ]
