# Generated by Django 2.1.11 on 2019-08-13 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20190813_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='file',
            field=models.FileField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
